name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18.19.0-alpine3.18

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Output versions
      run: node --version

    - name: Add Git
      run: |
        apk update
        apk add git
        git --version

    - name: Install NPM packages
      run: npm install

    - name: Build webpage
      run: npm run build

    - name: Push gh-pages branch changes
      run: |
        git config --global user.email "mikeyp.fennelly@gmail.com"
        git config --global user.name "Mikey Fennelly"
        cd gh-pages
        git add --all
        git commit -m "committing all"
        git push https://$GHA_PAT@github.com/mikeyfennelly1/CharlamagneDB/ gh-pages