name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 18.19.0-alpine3.18

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Output versions
      run: node --version

    - name: Add Git
      run: |
        apk update
        apk add git
        git --version

    - name: Install NPM packages
      run: npm install

    - name: Build webpage
      run: npm run build

    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ matrix.node-version }}
